version: '3.9'

volumes: 
  web:
    driver: local
    name: web
    driver_opts:
        type: none
        o: bind
        device: $HOME/data/website
  db:
    driver: local
    name: db
    driver_opts:
        type: none
        o: bind
        device: $HOME/data/database
        
services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    # ports:
    #   - 3306:3306
    volumes:
      - db:/var/lib/mysql/
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - backend

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    # build:
    #   context: requirements/wordpress
    #   args:
    #     - MARIADB_DATABASE=${MARIADB_DATABASE}
    #     - MARIADB_USER=${MARIADB_USER}
    #     - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    #     - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    #     - WORDPRESS_TITLE=${WORDPRESS_TITLE}
    #     - WORDPRESS_USER=${WORDPRESS_USER}
    #     - WORDPRESS_USER_MAIL=${WORDPRESS_USER_MAIL}
    #     - WORDPRESS_PASS=${WORDPRESS_PASS}
    #     - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER}
    #     - WORDPRESS_ADMIN_PASS=${WORDPRESS_ADMIN_PASS}
    #     - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL}
    #     - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
    #     - AUTH_KEY=${AUTH_KEY}
    #     - SECURE_AUTH_KEY=${SECURE_AUTH_KEY}
    #     - LOGGED_IN_KEY=${LOGGED_IN_KEY}
    #     - NONCE_KEY=${NONCE_KEY}
    #     - AUTH_SALT=${AUTH_SALT}
    #     - SECURE_AUTH_SALT=${SECURE_AUTH_SALT}
    #     - LOGGED_IN_SALT=${LOGGED_IN_SALT}
    #     - NONCE_SALT=${NONCE_SALT}
    # ports:
    #   - '9000:9000'
    volumes: 
      - web:/var/www/wordpress/
    depends_on:
      - mariadb
    restart: unless-stopped
    networks:
      - backend
    env_file:
      - .env
    environment:
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
  nginx:
    container_name: nginx
    build: requirements/nginx
    ports: 
      - "443:443"
    volumes:
      - web:/var/www/wordpress/
    networks:
      - backend
    depends_on:
      - wordpress
    restart: unless-stopped

networks:
  backend:
