version: '3.9'


volumes: 
#   web:
#     driver: local
#     name: web
#     driver_opts:
#         type: none
#         o: bind
#         device: /data/inception/website
  db:
    driver: local
    name: db
    driver_opts:
        type: none
        o: bind
        device: $HOME/data/inception/database
services:
  # nginx:
  #   build: requirements/nginx
  #   ports: 
  #     - "80:80"
  #     - "443:443"
  #   restart: always
  #   depends_on:
  #     - wordpress
  #   env_file:
  #     - .env
  #   volumes:
  #     - '~/home/${LINUX_USER}/data/inception/website:/'

  # wordpress:
  #   build: requirements/wordpress
  #   ports:
  #     - '8080:80'
  #     - '9000:9000'
  #   volumes: 
  #     - "~/home/${LINUX_USER}/data/inception/website/public:/myapps"
  #   depends_on:
  #     - mariadb
  #   restart: always
  #   env_file:
  #     - .env

  mariadb:
    
    build: requirements/mariadb
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql:delegated
    restart: always
    networks:
      - backend
    env_file:
      - .env


networks:
  backend: