version: '3.8'

services:
  # nginx:
  #   build: requirements/nginx
  #   ports: 
  #     - "80:80"
  #     - "443:443"
  #   restart: always
  #   depends_on:
  #     - wordpress
  #   env_file:
  #     - .env
  #   volumes:
  #     - '~/home/${LINUX_USER}/data/inception/website:/'

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    ports:
      - '9000:9000'
    volumes: 
      - web:/var/www/wordpress:delegated
    depends_on:
      - mariadb
    restart: always
    networks:
      - backend
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql:delegated
    restart: always
    networks:
      - backend
    env_file:
      - .env

volumes: 
  web:
    driver: local
    name: web
    driver_opts:
        type: none
        o: bind
        device: $HOME/data/website
  db:
    driver: local
    name: db
    driver_opts:
        type: none
        o: bind
        device: $HOME/data/database

networks:
  backend: