services:
  nginx:
    build: requirements/nginx
    ports: 
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - '~/home/${LINUX_USER}/data/inception/website:/'

  wordpress:
    build: requirements/wordpress
    ports:
      - '8080:80'
      - '9000:9000'
    volumes: 
      - "~/home/${LINUX_USER}/data/inception/website/public:/myapps"
    depends_on:
      - mariadb
    restart: always
    env_file:
      - .env

  mariadb:
    build: requirements/mariadb
    ports:
      - '3306:3306'
    env_file:
      - .env
    volumes:
      - "~/home/${LINUX_USER}/data/inception/database:/"
      - "~/home/${LINUX_USER}/data/inception/database:/etc/mysql"
    restart: always

